GET http://localhost:3000/address/7
Accept: application/json

###

GET http://localhost:3000/address/8
Accept: application/json

###

GET http://localhost:3000/address/9
Accept: application/json

###


POST http://localhost:3000/address
Content-Type: application/json

{
  "line1": "201 Main St",
  "city": "Los Angeles",
  "state": "CA",
  "zip": "90210"
}

###

PUT http://localhost:3000/address/8
Content-Type: application/json

{
  "line1": "201 Main St",
  "line2": "Suite 3",
  "city": "Los Angeles",
  "state": "CA",
  "zip": "90210"
}

###

DELETE http://localhost:3000/address/8
Content-Type: application/json

###
